version: '3.0'
services:
  web:
    image: ishtiaque/robishop
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env     
volumes:
  db-data: 
